#!/usr/bin/expect -f
# mv2r <host> <file> <remotepath>

set shorthost [lindex $argv 0]
set localloc [lindex $argv 1]
set remoteloc [lindex $argv 2]

set host [format %s.cs.wisc.edu $shorthost]
set username $env(WISC_CS_USERNAME)
set host [format %s@%s $username $host]
set password $env(WISC_CS_PASSWD)
set timeout -1

spawn scp $localloc $host:$remoteloc

expect {
    "Are you sure you want to continue connecting (yes/no" {
        send "yes\n"
        expect "Password:"
        send "$password\n"
    }
    "Password:" {
        send "$password\n"
    }
}

expect "Passcode or option (1-1):"
send "1\n"
interact